object Versions {
    const val androidCoreKtx = "1.9.0"
    const val androidLifecycleKtx = "2.6.2"
    const val androidActivityCompose = "1.7.2"
    const val composeBom = "2023.03.00"
    const val composeNavigation = "2.7.3"
    const val retrofit = "2.9.0"
    const val androidCoroutine = "1.3.9"
    const val hiltAndroid = "2.45"
    const val gson = "2.10.1"
    const val gsonSquare = "2.9.0"
    const val okhttp3Version = "4.10.0"
    const val composeRuntineLifecycle = "2.6.2"
    const val composeViewModel = "2.6.2"
    const val composeCoil = "2.4.0"
    const val composeHiltNavigation = "1.0.0"
    const val roomVersion = "2.5.2"
    const val kspTool = "1.8.10-1.0.9"

    const val junit5 = "5.9.3"
    const val assertK = "0.27.0"
    const val turbine = "1.0.0"
    const val junit5Compose = "1.0.0-SNAPSHOT"
    const val  mockk = "1.13.8"
}