name: BuildAPK

on:
  workflow_dispatch:
  #  pull_request:
  #   branches: [ master ]
  # push:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build with gradle
        run: ./gradlew assembleDebug -PNEWSAPP_API_KEY="${{secrets.NEWSAPP_API_KEY}}"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ci-cd.apk
          path: app/build/outputs/apk/debug/app-debug.apk